name: CI
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - README.md
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.8'
          - '3.11'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test_requirements.txt
        python -m pip install .
    - name: Run tests
      run: |
        pytest --color=yes
